import { StyleSheet } from "react-native";
import { colors, radii, spacing } from "@/lib/theme";

export const questionViewStyles = StyleSheet.create({
  header: {
    gap: spacing.sm,
  },
  // Progress bar track
  progressTrack: {
    height: 14,
    backgroundColor: colors.card,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: colors.ink,
    overflow: "hidden",
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 2, height: 2 },
    elevation: 2,
  },
  progressFill: {
    height: "100%",
    backgroundColor: colors.brand,
  },
  progressRow: {
    flexDirection: "row",
    gap: 6,
    marginBottom: spacing.xs,
  },
  progressDot: {
    flex: 1,
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.paperAlt,
    borderWidth: 1,
    borderColor: colors.ink,
  },
  progressDotActive: { backgroundColor: colors.brand },

  eyebrow: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.ink3,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    marginTop: spacing.sm,
  },

  // Speech-bubble question card
  bubbleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    marginTop: 8,
  },
  bubble: {
    flex: 1,
    padding: 14,
    backgroundColor: colors.card,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: colors.ink,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 3, height: 3 },
    elevation: 3,
  },
  bubbleLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.ink3,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  title: {
    fontSize: 19,
    fontWeight: "700",
    color: colors.ink,
    letterSpacing: -0.3,
    lineHeight: 26,
    marginTop: 4,
  },

  option: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: colors.card,
    borderRadius: radii.md,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 2.5,
    borderColor: colors.ink,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 3, height: 3 },
    elevation: 3,
  },
  optionDisabled: { opacity: 0.5 },
  optionPressed: {
    backgroundColor: colors.brandSoft,
    shadowColor: colors.brand,
  },
  optionDot: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: colors.paperAlt,
    borderWidth: 2,
    borderColor: colors.ink,
    alignItems: "center",
    justifyContent: "center",
  },
  optionDotText: {
    fontSize: 14,
    fontWeight: "900",
    color: colors.ink,
  },
  optionText: {
    flex: 1,
    fontSize: 16,
    color: colors.ink,
    lineHeight: 22,
    fontWeight: "700",
    letterSpacing: -0.2,
  },
});
