import { StyleSheet } from "react-native";
import { colors, radii, spacing } from "@/lib/theme";

export const weekCardStyles = StyleSheet.create({
  card: {
    backgroundColor: colors.card,
    padding: spacing.lg,
    borderRadius: radii.xl,
    borderWidth: 2,
    borderColor: colors.ink,
    gap: spacing.sm,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 3, height: 3 },
    elevation: 3,
  },
  cardComplete: {
    backgroundColor: colors.okSoft,
    shadowColor: colors.ok,
    shadowOffset: { width: 3, height: 3 },
  },
  cardUpcoming: {
    backgroundColor: colors.brandSoft,
    shadowColor: colors.brand,
    shadowOffset: { width: 3, height: 3 },
  },

  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
  },
  headerCol: { flex: 1 },
  badge: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.ink,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 3, height: 3 },
    elevation: 3,
  },
  badgeText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "900",
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    flexWrap: "wrap",
  },
  title: {
    fontSize: 16,
    fontWeight: "800",
    color: colors.ink,
    letterSpacing: -0.3,
  },
  objective: {
    fontSize: 13,
    color: colors.ink3,
    lineHeight: 18,
    marginTop: 2,
    fontWeight: "500",
  },
  statusPillDone: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: radii.pill,
    backgroundColor: colors.ok,
    borderWidth: 1.5,
    borderColor: colors.ink,
  },
  statusPillDoneText: {
    fontSize: 10,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  statusPillProgress: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: radii.pill,
    backgroundColor: "#FFE066",
    borderWidth: 1.5,
    borderColor: colors.ink,
  },
  statusPillProgressText: {
    fontSize: 10,
    fontWeight: "800",
    color: colors.ink,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },

  divider: {
    height: 1.5,
    backgroundColor: colors.line,
    marginVertical: 4,
  },
  fieldLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.ink4,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  modulesCol: { gap: spacing.sm },
  moduleRow: {
    flexDirection: "row",
    gap: spacing.sm,
    alignItems: "flex-start",
  },
  moduleCol: { flex: 1, gap: 2 },
  kindPill: {
    backgroundColor: colors.brandSoft,
    borderRadius: radii.sm,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginTop: 2,
    borderWidth: 1.5,
    borderColor: colors.ink,
  },
  kindPillText: {
    fontSize: 11,
    color: colors.brand,
    fontWeight: "800",
    textTransform: "lowercase",
  },
  moduleTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.ink,
  },
  moduleDesc: {
    fontSize: 13,
    color: colors.ink3,
    lineHeight: 18,
    fontWeight: "500",
  },

  metaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  metaPill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: colors.paperAlt,
    borderRadius: radii.pill,
    borderWidth: 1.5,
    borderColor: colors.ink,
  },
  metaPillText: {
    fontSize: 12,
    color: colors.ink,
    fontWeight: "600",
  },
  focusText: {
    fontSize: 12,
    color: colors.ink3,
    fontStyle: "italic",
  },

  cta: {
    marginTop: spacing.sm,
    borderRadius: radii.pill,
    borderWidth: 2,
    borderColor: colors.ink,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 3, height: 3 },
    elevation: 3,
    overflow: "hidden",
  },
  ctaGradient: {
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  ctaPressed: {
    transform: [{ translateX: 2 }, { translateY: 2 }],
  },
  ctaText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: -0.2,
  },
});
