import { StyleSheet } from "react-native";
import { colors, radii, spacing } from "@/lib/theme";

export const homeStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.paper },
  content: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 40,
    gap: 20,
  },

  // Header row
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerDay: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.ink3,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  headerName: {
    fontSize: 28,
    fontWeight: "900",
    color: colors.ink,
    letterSpacing: -0.8,
    lineHeight: 30,
    marginTop: 4,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: colors.brand,
    borderWidth: 2.5,
    borderColor: colors.ink,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 3, height: 3 },
    elevation: 3,
  },
  avatarText: { fontSize: 18, fontWeight: "900", color: "#fff" },

  // Streak hero card
  streakCard: {
    padding: 20,
    backgroundColor: colors.brand,
    borderRadius: 24,
    borderWidth: 2.5,
    borderColor: colors.ink,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 5, height: 5 },
    elevation: 5,
    overflow: "hidden",
  },
  streakTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  streakBadge: {
    width: 70,
    height: 70,
    borderRadius: 22,
    backgroundColor: "#FFE066",
    borderWidth: 2.5,
    borderColor: colors.ink,
    alignItems: "center",
    justifyContent: "center",
    transform: [{ rotate: "-4deg" }],
  },
  streakBadgeNum: {
    fontSize: 32,
    fontWeight: "900",
    color: colors.ink,
    letterSpacing: -1,
  },
  streakInfo: { flex: 1 },
  streakTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: "#fff",
    letterSpacing: -0.5,
    lineHeight: 24,
  },
  streakSub: {
    fontSize: 13,
    color: "rgba(255,255,255,0.95)",
    marginTop: 4,
    fontWeight: "600",
  },
  streakDots: { flexDirection: "row", gap: 6, marginTop: 16 },
  streakDotWrap: { flex: 1, alignItems: "center" },
  streakDotBox: {
    width: 26,
    height: 26,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: colors.ink,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  streakDotFilled: { backgroundColor: "#FFE066" },
  streakDotEmpty: { backgroundColor: "rgba(255,255,255,0.25)" },
  streakDotText: { fontSize: 12, fontWeight: "900", color: colors.ink },
  streakDotLabel: { fontSize: 10, fontWeight: "800", color: "rgba(255,255,255,0.85)" },

  // Section label
  sectionRow: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: "900",
    color: colors.ink,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  sectionMeta: { fontSize: 12, color: colors.ink3, fontWeight: "600" },

  // Today session card
  todayCard: {
    padding: 16,
    backgroundColor: colors.card,
    borderRadius: 22,
    borderWidth: 2.5,
    borderColor: colors.ink,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 4, height: 4 },
    elevation: 4,
  },
  todayCardTop: { flexDirection: "row", gap: 12, alignItems: "center" },
  todayEmoji: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: colors.flashSoft,
    borderWidth: 2,
    borderColor: colors.ink,
    alignItems: "center",
    justifyContent: "center",
  },
  todayEmojiText: { fontSize: 26 },
  todayInfo: { flex: 1 },
  todayTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: colors.ink,
    letterSpacing: -0.4,
    lineHeight: 22,
    marginTop: 6,
  },
  todaySub: { fontSize: 12, color: colors.ink3, marginTop: 2, fontWeight: "500" },
  progressTrack: {
    height: 8,
    backgroundColor: colors.paperAlt,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: colors.ink,
    overflow: "hidden",
    marginTop: 12,
  },
  progressFill: { height: "100%", backgroundColor: colors.brand },

  emptyDash: {
    padding: 14,
    borderRadius: 18,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: colors.ink3,
    alignItems: "center",
  },
  emptyDashText: { fontSize: 14, fontWeight: "800", color: colors.ink3 },

  // Diagnostics
  diagRow: { flexDirection: "row", gap: 6, flexWrap: "wrap" },
  diagDetail: { fontSize: 11, color: colors.ink4 },
  diagError: { fontSize: 11, color: colors.warn },

  // Sign out
  signOut: {
    paddingVertical: 12,
    alignItems: "center",
    borderRadius: radii.md,
    borderWidth: 2,
    borderColor: colors.ink4,
    borderStyle: "dashed",
  },
  signOutText: { fontSize: 14, color: colors.ink3, fontWeight: "600" },

  // Legacy compat fields used by the existing index.tsx render path
  hero: {},
  heroEyebrow: { fontSize: 12, fontWeight: "800", color: colors.ink3, letterSpacing: 2, textTransform: "uppercase" },
  heroTitle: { fontSize: 28, fontWeight: "900", color: colors.ink, letterSpacing: -0.8 },
  heroSubtitle: { fontSize: 15, color: colors.ink3 },
  heroCtaRow: { flexDirection: "row", gap: 8, flexWrap: "wrap" },
  heroCta: {
    backgroundColor: colors.brand,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: radii.pill,
    borderWidth: 2,
    borderColor: colors.ink,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 3, height: 3 },
    elevation: 3,
  },
  heroCtaText: { color: "#fff", fontSize: 14, fontWeight: "800" },
  heroCtaGhost: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: radii.pill,
    borderWidth: 2,
    borderColor: colors.ink,
    backgroundColor: colors.card,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 3, height: 3 },
    elevation: 3,
  },
  heroCtaGhostText: { color: colors.ink, fontSize: 14, fontWeight: "800" },
  tierBadgeRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  tierBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.ink,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: radii.pill,
    gap: 6,
  },
  tierBadgeDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.brand },
  tierBadgeText: { color: "#fff", fontSize: 11, fontWeight: "800", letterSpacing: 0.6, textTransform: "uppercase" },
  tierBadgeMeta: { color: "rgba(255,255,255,0.7)", fontSize: 11, fontWeight: "600" },
  card: {
    backgroundColor: colors.card,
    padding: spacing.lg,
    borderRadius: radii.lg,
    borderWidth: 2,
    borderColor: colors.ink,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 3, height: 3 },
    elevation: 3,
  },
  emptyCard: { alignItems: "flex-start", paddingVertical: spacing.xl, gap: spacing.sm },
  emptyEmoji: { fontSize: 36 },
  emptyCta: {
    marginTop: spacing.sm,
    backgroundColor: colors.brand,
    paddingHorizontal: spacing.lg,
    paddingVertical: 10,
    borderRadius: radii.pill,
    borderWidth: 2,
    borderColor: colors.ink,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 3, height: 3 },
    elevation: 3,
  },
  emptyCtaText: { color: "#fff", fontWeight: "800", fontSize: 15 },
});
