import { StyleSheet } from "react-native";
import { colors, spacing } from "@/lib/theme";

export const progressScreenStyles = StyleSheet.create({
  content: {
    padding: spacing.lg,
    gap: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  heroBlock: { gap: spacing.xs },
  heroEyebrow: {
    fontSize: 12,
    fontWeight: "900",
    color: colors.ink3,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  heroTitle: {
    fontSize: 30,
    fontWeight: "900",
    color: colors.ink,
    letterSpacing: -0.4,
    lineHeight: 36,
  },
  heroSubtitle: {
    fontSize: 14,
    color: colors.ink3,
    lineHeight: 20,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: "900",
    color: colors.ink3,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: spacing.xs,
  },
  curriculumCard: {
    backgroundColor: colors.card,
    borderRadius: 16,
    padding: spacing.lg,
    gap: spacing.xs,
    borderWidth: 2,
    borderColor: colors.ink,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 4, height: 4 },
    elevation: 4,
  },
  curriculumRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1.5,
    borderBottomColor: "rgba(26,20,16,0.10)",
  },
  curriculumRowLast: { borderBottomWidth: 0 },
  curriculumEmoji: { fontSize: 22, width: 32, textAlign: "center" },
  curriculumBody: { flex: 1, gap: 2 },
  curriculumTitle: { fontSize: 15, color: colors.ink, fontWeight: "700" },
  curriculumMeta: { fontSize: 12, color: colors.ink3 },
  curriculumScore: {
    fontSize: 14,
    fontWeight: "900",
    color: colors.brand,
    minWidth: 44,
    textAlign: "right",
  },
  tipCard: {
    backgroundColor: colors.brandSoft,
    borderRadius: 14,
    padding: spacing.md,
    gap: 4,
    borderWidth: 1.5,
    borderColor: colors.ink,
  },
  tipLabel: {
    fontSize: 11,
    fontWeight: "900",
    color: colors.brand,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  tipText: { fontSize: 13, color: colors.ink2, lineHeight: 18 },
  empty: {
    fontSize: 13,
    color: colors.ink3,
    fontStyle: "italic",
    paddingVertical: spacing.sm,
  },
});
