import { StyleSheet } from "react-native";
import { colors, spacing } from "@/lib/theme";

export const progressStripStyles = StyleSheet.create({
  card: {
    backgroundColor: colors.card,
    borderRadius: 16,
    padding: spacing.lg,
    gap: spacing.sm,
    borderWidth: 2,
    borderColor: colors.ink,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 3, height: 3 },
    elevation: 3,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  eyebrow: {
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: colors.ink3,
  },
  replanBadge: {
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.4,
    textTransform: "uppercase",
    color: colors.brand,
    backgroundColor: colors.brandSoft,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: colors.ink,
  },
  statsRow: {
    flexDirection: "row",
    alignItems: "stretch",
    paddingVertical: spacing.sm,
  },
  stat: { flex: 1, alignItems: "center", gap: 2 },
  statValue: { fontSize: 16, fontWeight: "900", color: colors.ink },
  statLabel: { fontSize: 11, color: colors.ink3, letterSpacing: 0.2 },
  statDivider: {
    width: 1.5,
    backgroundColor: "rgba(26,20,16,0.12)",
    marginVertical: 4,
  },
  lastActive: { fontSize: 12, color: colors.ink4 },
  actionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  ctaBtn: {
    flex: 1,
    minWidth: 140,
    backgroundColor: colors.brand,
    paddingVertical: 10,
    paddingHorizontal: spacing.md,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: colors.ink,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 2, height: 2 },
    elevation: 2,
  },
  ctaBtnDisabled: { opacity: 0.5 },
  ctaBtnText: { color: "#fff", fontSize: 14, fontWeight: "800" },
  ghostBtn: {
    flex: 1,
    minWidth: 120,
    backgroundColor: colors.card,
    paddingVertical: 10,
    paddingHorizontal: spacing.md,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: colors.ink,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 2, height: 2 },
    elevation: 2,
  },
  ghostBtnText: { color: colors.ink, fontSize: 14, fontWeight: "700" },
});
