import { StyleSheet } from "react-native";
import { colors, spacing } from "@/lib/theme";

export const finishedViewStyles = StyleSheet.create({
  hero: {
    gap: spacing.xs,
  },
  eyebrow: {
    fontSize: 12,
    fontWeight: "900",
    color: colors.ink3,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  title: {
    fontSize: 32,
    fontWeight: "900",
    color: colors.ink,
    letterSpacing: -0.4,
    lineHeight: 38,
  },
  sub: {
    fontSize: 15,
    color: colors.ink3,
    lineHeight: 22,
  },

  scoreCard: {
    backgroundColor: colors.card,
    padding: spacing.xl,
    borderRadius: 20,
    alignItems: "center",
    gap: spacing.md,
    borderWidth: 2.5,
    borderColor: colors.ink,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 5, height: 5 },
    elevation: 5,
  },
  scoreNumber: {
    fontSize: 72,
    fontWeight: "900",
    color: colors.brand,
    letterSpacing: -3,
    lineHeight: 80,
  },
  scoreLabel: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.ink3,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },

  chart: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "center",
    gap: spacing.xs,
    marginTop: spacing.sm,
    width: "100%",
    minHeight: 120,
  },
  chartCol: {
    flex: 1,
    maxWidth: 36,
    alignItems: "center",
    gap: spacing.xs,
  },
  chartBarTrack: {
    width: "100%",
    height: 96,
    borderRadius: 8,
    backgroundColor: colors.paperAlt,
    borderWidth: 1.5,
    borderColor: colors.ink,
    justifyContent: "flex-end",
    overflow: "hidden",
  },
  chartBar: {
    width: "100%",
    borderRadius: 6,
  },
  chartLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.ink3,
  },
  chartLegend: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: spacing.md,
    marginTop: spacing.xs,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  legendSwatch: {
    width: 10,
    height: 10,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: colors.ink,
  },
  legendText: {
    fontSize: 12,
    color: colors.ink3,
    fontWeight: "600",
  },

  recapCard: {
    backgroundColor: colors.card,
    padding: spacing.lg,
    borderRadius: 16,
    gap: spacing.sm,
    borderWidth: 2,
    borderColor: colors.ink,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 3, height: 3 },
    elevation: 3,
  },
  recapTitle: {
    fontSize: 11,
    fontWeight: "900",
    color: colors.ink3,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  recapRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  recapDot: {
    width: 10,
    height: 10,
    borderRadius: 3,
    borderWidth: 1.5,
    borderColor: colors.ink,
  },
  recapText: {
    flex: 1,
    fontSize: 15,
    color: colors.ink2,
    lineHeight: 21,
  },

  bonusCard: {
    backgroundColor: colors.mcSoft,
    padding: spacing.lg,
    borderRadius: 16,
    gap: spacing.sm,
    borderWidth: 2,
    borderColor: colors.ink,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 4, height: 4 },
    elevation: 4,
  },
  bonusEyebrow: {
    fontSize: 11,
    fontWeight: "900",
    color: colors.mc,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  bonusTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: colors.ink,
    letterSpacing: -0.3,
  },
  bonusBlurb: {
    fontSize: 14,
    color: colors.ink2,
    lineHeight: 20,
  },
});
