import { StyleSheet } from "react-native";
import { colors, spacing } from "@/lib/theme";

export const lessonViewStyles = StyleSheet.create({
  container: {
    gap: spacing.lg,
  },
  header: {
    gap: spacing.sm,
  },
  conceptLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: colors.ink3,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  title: {
    fontSize: 28,
    fontWeight: "900",
    color: colors.ink,
    letterSpacing: -0.4,
    lineHeight: 34,
  },
  card: {
    backgroundColor: colors.card,
    borderWidth: 2,
    borderColor: colors.ink,
    borderRadius: 16,
    padding: spacing.xl,
    gap: spacing.lg,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 4, height: 4 },
    elevation: 4,
  },
  intro: {
    fontSize: 16,
    lineHeight: 24,
    color: colors.ink2,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.brand,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: spacing.xs,
  },
  bulletRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  bulletDot: {
    fontSize: 15,
    lineHeight: 22,
    color: colors.brand,
    fontWeight: "900",
  },
  bulletText: {
    flex: 1,
    fontSize: 15,
    lineHeight: 22,
    color: colors.ink2,
  },
  exampleBox: {
    backgroundColor: colors.card,
    borderWidth: 2,
    borderColor: colors.ink,
    borderRadius: 12,
    padding: spacing.lg,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 3, height: 3 },
    elevation: 3,
  },
  exampleText: {
    fontSize: 15,
    lineHeight: 22,
    color: colors.ink,
    fontStyle: "italic",
  },
  pitfallBox: {
    backgroundColor: colors.brandSoft,
    borderWidth: 2,
    borderColor: colors.ink,
    borderRadius: 12,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  pitfallLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.brand,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  nextUp: {
    fontSize: 14,
    lineHeight: 20,
    fontStyle: "italic",
    color: colors.ink3,
    paddingHorizontal: spacing.xs,
  },
});
