import { StyleSheet } from "react-native";
import { colors, spacing } from "@/lib/theme";

export const listenChoiceStyles = StyleSheet.create({
  audioCard: {
    backgroundColor: colors.card,
    borderWidth: 2,
    borderColor: colors.ink,
    borderRadius: 16,
    padding: spacing.lg,
    gap: spacing.md,
    alignItems: "center",
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 3, height: 3 },
    elevation: 3,
  },
  promptNative: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.ink,
    textAlign: "center",
    lineHeight: 22,
  },
  playButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    backgroundColor: colors.flash,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: colors.ink,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 3, height: 3 },
    elevation: 3,
  },
  playButtonActive: {
    backgroundColor: colors.brand,
  },
  playButtonPressed: {
    shadowOffset: { width: 1, height: 1 },
    transform: [{ translateX: 2 }, { translateY: 2 }],
  },
  playButtonDisabled: {
    opacity: 0.5,
  },
  playButtonIcon: {
    fontSize: 22,
    color: "#fff",
  },
  playButtonLabel: {
    fontSize: 15,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: 0.3,
  },
  audioError: {
    color: colors.warn,
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  audioTextFallback: {
    color: colors.ink3,
    fontSize: 16,
    fontStyle: "italic",
    textAlign: "center",
    paddingTop: spacing.xs,
  },
  lockHint: {
    color: colors.ink3,
    fontSize: 12,
    fontStyle: "italic",
    textAlign: "center",
    paddingTop: spacing.xs,
  },
  transcriptCard: {
    backgroundColor: colors.flashSoft,
    borderWidth: 1.5,
    borderColor: colors.ink,
    borderRadius: 12,
    padding: spacing.md,
    gap: 4,
  },
  transcriptLabel: {
    fontSize: 11,
    fontWeight: "900",
    color: colors.flash,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  transcriptText: {
    fontSize: 16,
    color: colors.ink2,
    lineHeight: 22,
  },
});
