import { StyleSheet } from "react-native";
import { colors, spacing } from "@/lib/theme";

export const multipleChoiceStyles = StyleSheet.create({
  prompt: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.ink,
    lineHeight: 26,
    backgroundColor: colors.card,
    borderWidth: 2,
    borderColor: colors.ink,
    borderRadius: 16,
    padding: spacing.lg,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 3, height: 3 },
    elevation: 3,
  },
  option: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    backgroundColor: colors.card,
    borderRadius: 14,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderWidth: 2,
    borderColor: colors.ink,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 3, height: 3 },
    elevation: 3,
  },
  optionPressed: {
    shadowOffset: { width: 1, height: 1 },
    transform: [{ translateX: 2 }, { translateY: 2 }],
  },
  optionChosen: {
    borderColor: colors.mc,
    backgroundColor: colors.mcSoft,
  },
  optionCorrect: {
    borderColor: colors.ok,
    backgroundColor: colors.okSoft,
  },
  optionWrong: {
    borderColor: colors.warn,
    backgroundColor: colors.warnSoft,
  },
  optionFaded: { opacity: 0.45 },
  optionDot: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: colors.paperAlt,
    borderWidth: 2,
    borderColor: colors.ink,
    alignItems: "center",
    justifyContent: "center",
  },
  optionDotCorrect: { backgroundColor: colors.ok },
  optionDotWrong: { backgroundColor: colors.warn },
  optionDotText: {
    fontSize: 13,
    fontWeight: "900",
    color: colors.ink,
  },
  optionDotTextOnAccent: { color: "#fff" },
  optionText: {
    flex: 1,
    fontSize: 16,
    fontWeight: "600",
    color: colors.ink,
    lineHeight: 22,
  },
});
