import { StyleSheet } from "react-native";
import { colors, spacing } from "@/lib/theme";

export const videoChoiceStyles = StyleSheet.create({
  videoCard: {
    backgroundColor: colors.ink,
    borderWidth: 2.5,
    borderColor: colors.ink,
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 4, height: 4 },
    elevation: 4,
  },
  webview: {
    width: "100%",
    height: 210,
    backgroundColor: colors.ink,
  },
  videoFooter: {
    backgroundColor: colors.ink,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    gap: spacing.md,
  },
  videoLabel: {
    fontSize: 11,
    fontWeight: "900",
    color: "rgba(255,255,255,0.55)",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  watchedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: colors.ok,
    paddingHorizontal: spacing.md,
    paddingVertical: 4,
    borderRadius: 999,
  },
  watchedBadgeText: {
    fontSize: 11,
    fontWeight: "900",
    color: "#fff",
    letterSpacing: 0.4,
  },
  watchCtaRow: {
    alignItems: "center",
  },
  watchCta: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    backgroundColor: colors.warn,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: colors.ink,
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 3, height: 3 },
    elevation: 3,
  },
  watchCtaPressed: {
    shadowOffset: { width: 1, height: 1 },
    transform: [{ translateX: 2 }, { translateY: 2 }],
  },
  watchCtaIcon: {
    fontSize: 20,
  },
  watchCtaText: {
    fontSize: 15,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: 0.2,
  },
  promptText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.ink,
    lineHeight: 22,
  },
  lockHint: {
    color: colors.ink3,
    fontSize: 12,
    fontStyle: "italic",
    textAlign: "center",
    paddingTop: spacing.xs,
  },
  noVideoCard: {
    backgroundColor: colors.paperAlt,
    borderWidth: 2,
    borderColor: colors.ink,
    borderRadius: 14,
    padding: spacing.lg,
    alignItems: "center",
    gap: spacing.sm,
  },
  noVideoIcon: { fontSize: 32 },
  noVideoText: {
    fontSize: 13,
    color: colors.ink3,
    textAlign: "center",
    lineHeight: 18,
  },
});
