import { StyleSheet } from "react-native";
import { colors, spacing } from "@/lib/theme";

export const videoChoiceStyles = StyleSheet.create({
  videoCard: {
    backgroundColor: colors.ink,
    borderWidth: 2.5,
    borderColor: colors.ink,
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: colors.ink,
    shadowOpacity: 1,
    shadowRadius: 0,
    shadowOffset: { width: 4, height: 4 },
    elevation: 4,
  },
  videoCardPressed: {
    shadowOffset: { width: 1, height: 1 },
    transform: [{ translateX: 3 }, { translateY: 3 }],
  },
  thumbnail: {
    width: "100%",
    height: 200,
    backgroundColor: "#000",
  },
  thumbnailFallback: {
    width: "100%",
    height: 200,
    backgroundColor: "#111",
    alignItems: "center",
    justifyContent: "center",
  },
  thumbnailFallbackIcon: {
    fontSize: 48,
  },
  videoOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 200,
    alignItems: "center",
    justifyContent: "center",
  },
  playBtn: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "rgba(255,0,0,0.9)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: "#fff",
  },
  playBtnIcon: {
    fontSize: 24,
    color: "#fff",
    marginLeft: 4,
  },
  videoFooter: {
    backgroundColor: colors.ink,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  videoLabel: {
    fontSize: 11,
    fontWeight: "900",
    color: "rgba(255,255,255,0.55)",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  videoHint: {
    fontSize: 11,
    fontWeight: "700",
    color: "rgba(255,255,255,0.4)",
    letterSpacing: 0.4,
  },
  promptText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.ink,
    lineHeight: 22,
  },
  noVideoCard: {
    backgroundColor: colors.paperAlt,
    borderWidth: 2,
    borderColor: colors.ink,
    borderRadius: 14,
    padding: spacing.lg,
    alignItems: "center",
    gap: spacing.sm,
  },
  noVideoIcon: { fontSize: 32 },
  noVideoText: {
    fontSize: 13,
    color: colors.ink3,
    textAlign: "center",
    lineHeight: 18,
  },
});
